### ISSUE TITLE
请问是发布按钮是失效了吗， 需要更新代码嘛

### ISSUE THREAD

**Issue by laoxue0608** [kebenxiaoming/matrix#12]
[+]正在上传-------扑克牌上的Q代表什么.mp4
[-] 正在打开主页...
Traceback (most recent call last):
  File "/Users/lixiaobo/matrix/publish_video_queue.py", line 262, in <module>
    asyncio.run(app.main(), debug=False) 
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/lixiaobo/matrix/douyin_uploader/main.py", line 398, in main
    await self.upload(playwright)
  File "/Users/lixiaobo/matrix/douyin_uploader/main.py", line 274, in upload
    upload_button = await page.wait_for_selector(".upload-btn--9eZLd", state="visible", timeout=10000)
  File "/Users/lixiaobo/matrix/venv/lib/python3.9/site-packages/playwright/async_api/_generated.py", line 8158, in wait_for_selector
    await self._impl_obj.wait_for_selector(
  File "/Users/lixiaobo/matrix/venv/lib/python3.9/site-packages/playwright/_impl/_page.py", line 426, in wait_for_selector
    return await self._main_frame.wait_for_selector(**locals_to_params(locals()))
  File "/Users/lixiaobo/matrix/venv/lib/python3.9/site-packages/playwright/_impl/_frame.py", line 323, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "/Users/lixiaobo/matrix/venv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "/Users/lixiaobo/matrix/venv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 520, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.wait_for_selector: Timeout 10000ms exceeded.
Call log:
waiting for locator(".upload-btn--9eZLd") to be visible

**Comment by kebenxiaoming** [comment]
抖音发布视频发布已经修复更新了，但是这个版本无法替换抖音视频封面图，请注意
