### ISSUE TITLE
快手登录报错

### ISSUE THREAD

**Issue by fengshaoqi** [kebenxiaoming/matrix#4]
Traceback (most recent call last):
  File "D:\pycharmWorkSpace\matrix\ks_uploader\main.py", line 132, in ks_cookie_gen
    third_id_cont = await page.get_by_text("快手号：").inner_text()
  File "D:\pycharmWorkSpace\matrix\.venv\lib\site-packages\playwright\async_api\_generated.py", line 16267, in inner_text
    return mapping.from_maybe_impl(await self._impl_obj.inner_text(timeout=timeout))
  File "D:\pycharmWorkSpace\matrix\.venv\lib\site-packages\playwright\_impl\_locator.py", line 444, in inner_text
    return await self._frame.inner_text(
  File "D:\pycharmWorkSpace\matrix\.venv\lib\site-packages\playwright\_impl\_frame.py", line 618, in inner_text
    return await self._channel.send("innerText", locals_to_params(locals()))
  File "D:\pycharmWorkSpace\matrix\.venv\lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "D:\pycharmWorkSpace\matrix\.venv\lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Locator.inner_text: Timeout 30000ms exceeded.
Call log:
waiting for get_by_text("快手号：")

执行一次查询
Traceback (most recent call last):
  File "D:\pycharmWorkSpace\matrix\user_queue_login.py", line 90, in <module>
    time.sleep(5)
KeyboardInterrupt

**Comment by kebenxiaoming** [comment]
超时了，可能是登录后刷新页面没成功，重试一次正常不？测试的时候最好设置headless为False来测试

**Comment by kebenxiaoming** [comment]
超时了，可能是登录后刷新页面没成功，重试一次正常不？测试的时候最好设置headless为False来测试

**Comment by fengshaoqi** [comment]
好的，谢谢，好像快手还没有完全可以发布，对吧？

**Comment by kebenxiaoming** [comment]
> 好的，谢谢，好像快手还没有完全可以发布，对吧？

对，还没有完全完成，你也可以自己用headless=False设置成可视浏览器界面来调试
